version: '3.2'

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - ./init_db/:/docker-entrypoint-initdb.d/

    app:
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
            docker: "true"
        ports:
<<<<<<< HEAD
            - 8000:80
=======
            - "8080:80"
        volumes: 
            - type: bind
              source: .
              target: /var/www/html
>>>>>>> 2240f9bb5a37fdf5ee4c14aea97dd6811863f0c7
        depends_on:
        - db
        env_file:
            - .env
volumes:
    init_db:
           
