version: '3'

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - ./init_db/:/docker-entrypoint-initdb.d/

    app:
        build: .
        environment:
            docker: "true"
        ports:
            - 8080:80
        depends_on:
        - db
        env_file:
            - .env
volumes:
    init_db:
           
