version: '3'

services:
    hidroponica:
        build: .
        container_name: hidroponica
        environment:
            docker: "true"
        ports:
            - 8080:80
        depends_on:
        - mysql
    mysql:
        image: mariadb:10.4
        container_name: mysql
        ports:
            - 3301:3306
        environment:
            MYSQL_DATABASE: hidroponica
            MYSQL_ROOT_PASSWORD: DaVS7a18*
        
           